### PR TITLE
Explain $ and $$ tokens

### PR DESCRIPTION
**Pull request by shanavas786**
Explain what do $ and $$ mean in expression 510-($-$$).

Explanation from [NASM](http://www.nasm.us/doc/nasmdoc3.html#section-3.5)

### CODE REVIEW

**Comment by nicholasday** [comment]
Thanks for the addition :smile:. I added comments about `$` and `$$` to the other repo [tutorialsbynick](https://github.com/TutorialsByNick/tutorialsbynick) because I forgot to change the make a new issue link in the article to the other repo. (I don't make html code changes in this one anymore.)

What did you think of the tutorial?

**Comment by shanavas786** [comment]
Was a good starting point. Heading through [phill-opp's](http://os.phil-opp.com/) blogs

**Comment by nicholasday** [comment]
I plan to continue my series on writing an operating system, so please subscribe!

**Comment by shanavas786** [comment]
Sure :)

**Pull request closed without merging**
